services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd sample-react && yarn start'
    ports:
      - 8000:3000
    tty: true
